[build]
  publish = "dist"
  command = "eleventy"


[[headers]]
  for = "/static/fonts/*.woff2"
  [headers.values]
    # cache for one month
    cache-control = "public, max-age=2592000"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
  # either "warn" or "error"
  on404 = "warn"
  cacheKey = "no-more-404-v1"

