# Netlify CMS Configuration File

backend:
  name: git-gateway
  branch: master

locale: "cs"

site_url: https://www.nalezenovmyslance.cz/

media_folder: "static/img"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Články" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulek", name: "title", widget: "string" }
      - {
          label: "Den publikování",
          name: "date",
          widget: "date",
          date_format: "DD.MM.YYYY",
        }
      - { label: "Tagy", name: "tags", widget: "list", default: ["post"] }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Stránky"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - {
          label: "Den publikování",
          name: "date",
          widget: "date",
          date_format: "DD.MM.YYYY",
        }
      - { label: "Odkaz", name: "permalink", widget: "string" }
      - label: "Navigace" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Klíč", name: "key", widget: "string" }
          - { label: "Pořadí", name: "order", widget: "number", default: 0 }
      - { label: "Text", name: "body", widget: "markdown", required: false }
